👍
echo-youn/vue-todo-app pull request #3
Opened 2022-03-05 01:03 UTC by BlackDoGumjung

:$

2022-03-05 10:46 UTC, echo-youn requested changes

2022-03-05 10:46 UTC, echo-youn commented on src/App.vue
> +import ToordieApp from './components/ToordieApp.vue'
App.vue가 아무 역할이 없는 컴포넌트네요
todo-app: ToordieApp을 호출하는 대신 App.vue에 구현해보세요!

2022-03-05 10:49 UTC, echo-youn commented on src/components/ToordieApp.vue
> +  },
메서드 사이의 공백이 너무 넓은 것 같아요! ㅋㅋ;

2022-03-05 10:51 UTC, echo-youn requested changes

2022-03-05 10:51 UTC, echo-youn commented on src/components/ToordieApp.vue
> +  name: "toordielist",
camelCase로 작성해주세요!

2022-03-05 10:54 UTC, echo-youn commented on src/components/ToordieApp.vue
> +      statuses: ["todo", "doing", "done"],
상태를 부르는 단어가 두가지가 있는데, `status`와 `state`가 있습니다.
이거에 대해서 갑론을박 얘기가 많은데 개인적으로는 `state`가 더 읽기도 좋고 복수형도 깔끔한거 같아요.
그리고 `status`는 It's my status(state). 비교해봤을때 자연스러운거 같아요 ㅋㅋ

2022-03-06 04:08 UTC, BlackDoGumjung commented on src/App.vue
> +import ToordieApp from './components/ToordieApp.vue'
선생님 저 안 그래도 제가 본 예제에서 굳이 임폴트해서 써서, 
앱뷰에 바로 작성해도 되는지 물어보려고 했는데 ㅋㅋㅋㅋ 
오늘 저녁에 질문하겠읍니다....!!

2022-03-06 11:34 UTC, echo-youn commented on src/components/ToordieApp.vue
> +  name: "toordielist",
camelCase
PascalCase
kebab-case
snake_case

2022-03-06 11:50 UTC, echo-youn approved these changes
LGTM 👍

2022-03-06 11:51 UTC, merged